### ISSUE TITLE
[ERROR] Unknown error occurred.

### ISSUE THREAD

**Issue by rexuk** [yck1509/ConfuserEx#255] opened 2015-06-09 10:51 UTC
using the ConfuserEx v0.5.0

[ERROR] Unknown error occurred.
Exception: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at Confuser.Renamer.BAML.BAMLStringReference.Rename(String oldName, String newName) in e:\Source\Public\Confuser2\Confuser.Renamer\BAML\BAMLStringReference.cs:line 15
   at Confuser.Renamer.Analyzers.WPFAnalyzer.PreRename(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\WPFAnalyzer.cs:line 59
   at Confuser.Renamer.RenamePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\RenamePhase.cs:line 25
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 138
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 216
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162
Failed at 11:43, 0:02 elapsed.

**Comment by yck1509** [comment] 2015-06-27 13:40
Duplicate of #242

**Closed** 2015-06-27 13:43 UTC
